server:
  port: 9003

spring:
  application:
    name: examination-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/exam_schedules

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    fetch-registry: true
    register-with-eureka: true
    eviction-interval-timer-in-ms: 10000

  messages:
    notFound: "No record found"
    success: "Operation successful"
    error: "An error occurred"

logging:
  level:
    root: INFO
    com.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true



