server:
  port: 8082

spring:
  application:
    name: examination-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/exam_schedules

  mail:
    host: smtp.gmail.com
    port: 587
    username: vanikumari.gulla2@gmail.com   # Your Gmail ID
    password: sbdroggzjfompwkp              # App password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    eviction-interval-timer-in-ms: 10000

mail:
  from: vanikumari.gulla2@gmail.com
  to: junnu3714@gmail.com

logging:
  level:
    root: INFO
    com.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

custom:
  messages:
    notFound: "No record found"
    success: "Operation successful"
    error: "An error occurred"
