server:
  port: 8081

spring:
  application:
    name: student-service

  datasource:
    url: jdbc:mysql://localhost:3306/studentsdata
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: Vanikumari.gulla2@gmail.com
    password: sbdroggzjfompwkp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: student-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    config:
      fail-fast: true
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    eviction-interval-timer-in-ms: 10000

resilience4j:
  retry:
    instances:
      studentRetry:
        max-attempts: 2                # total 2 attempts (1 original + 1 retry)
        wait-duration: 1s              # wait between retry attempts
        retry-exceptions:
          - java.lang.Exception        # retry only on general exceptions
        ignore-exceptions:
          - com.example.student.service.exception.StudentNotFoundException

  circuitbreaker:
    instances:
      studentCB:
        failure-rate-threshold: 50                             # open if 50% of requests fail
        minimum-number-of-calls: 3                             # CB activates after at least 2 calls
        sliding-window-size: 3                                 # consider 4 latest calls for failure rate
        wait-duration-in-open-state: 10s                       # stay OPEN for 10 seconds
        permitted-number-of-calls-in-half-open-state: 1        # test with 1 call before closing
        automatic-transition-from-open-to-half-open-enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.example: DEBUG
